module.exports = {
  someSidebar: {
    resources: [
      'free-websites-1',
      'html-2',
      'css-3',
      'free-media-4',
      'javascript-5',
      'react-6',
      // 'markdown-features',
      'nextjs-7',
      'job-hunt-8',
      'career-9',
      'computer-science-10',
      'aws-11',
      'php-12',
      'git-13',
      'coding-exercises-14',
      'android-15',
      'node-16',
      'python-17',
      'blog-18',
      'unity-18',
    ],
  },
}
